export const RULE_ALIASES: Record<string, string[]> = {
  purple: ["purple", "rouge noire", "rouge et noire"],
  "purple couleur": [
    "purple couleur",
    "couleur annoncée",
    "couleur annoncee",
    "couleur + atout",
  ],
  "purple atout": [
    "purple atout",
    "rouge noire atout",
    "rouge noire et atout",
  ],
  "purple bout": ["purple bout", "bout", "purple avec bout"],
  poignée: [
    "poignée",
    "poignee",
    "atouts consécutifs",
    "atouts consecutifs",
  ],
  "double poignée": ["double poignée", "double poignee", "5 atouts"],
  "triple poignée": [
    "triple poignée",
    "triple poignee",
    "6 atouts",
    "cul sec atouts",
  ],
  "misère d’atout": [
    "misère",
    "misere",
    "sans atout",
    "6 cartes sans atout",
  ],
  petit: ["petit", "le petit", "accent du sud"],
  "petit au bout": ["petit au bout", "dernier pli", "petit dernier pli"],
  "poteau ou bout": [
    "poteau",
    "bout",
    "annoncer un bout",
    "annoncer un poteau",
  ],
  "je pisse": [
    "je pisse",
    "pisse",
    "3 atouts d’affilée",
    "3 atouts d'affilee",
  ],
  "j’ouvre à une couleur": [
    "j’ouvre",
    "j'ouvre",
    "ouvre couleur",
    "ouvrir à une couleur",
  ],
  "21": ["21", "vingt-et-un", "vingt et un"],
  excuse: ["excuse", "joker"],
  "défi du dealer": [
    "défi dealer",
    "defi dealer",
    "paquet sur la tête",
    "paquet sur sa tete",
  ],
  "tu gardes": [
    "tu gardes",
    "tu gardes sans",
    "tu gardes contre",
    "x2",
    "x4",
    "x8",
  ],
  sandwich: [
    "sandwich",
    "encadrée",
    "encadree",
    "même valeur",
    "meme valeur",
  ],
  "ça coupe": ["ça coupe", "ca coupe", "coupe", "prochaine carte atout"],
  dealer: [
    "dealer",
    "regarde les cartes",
    "changer l’ordre",
    "changer l'ordre",
  ],
  "avis du dealer": [
    "avis du dealer",
    "vote",
    "majorité",
    "majorite",
    "destin liés",
    "destin lies",
  ],
  rois: [
    "roi",
    "rois",
    "partager les gorgées",
    "partager les gorgees",
  ],
  épicerie: [
    "épicier",
    "epicier",
    "épicerie",
    "epicerie",
    "épicerie fine",
    "epicerie fine",
  ],
  chien: [
    "chien",
    "remplacer ses gorgées",
    "remplacer ses gorgees",
    "6 cartes maximum",
  ],
  paquet: ["paquet", "merci", "verre d’eau", "verre d'eau"],
  divers: [
    "perdu",
    "ne sait plus jouer",
    "renverse un verre",
    "tu la chutes",
  ],
};
