export const RULE_ALIASES: Record<string, string[]> = {
  "but du jeu": [
    "but du jeu",
    "objectif",
    "comment jouer",
    "comment fonctionne le jeu",
  ],
  "mise en place": ["mise en place", "préparation", "preparation", "commencer une partie"],
  "début et ordre d'un tour": [
    "déroulement d'un tour",
    "deroulement d'un tour",
    "ordre du tour",
    "comment se passe un tour",
  ],
  "rouge ou noir": [
    "rouge ou noir",
    "annonce rouge",
    "annonce noir",
    "coeur carreau pique trefle",
  ],
  "purple classique": [
    "purple",
    "purple classique",
    "rouge noire",
    "rouge et noire",
  ],
  "plus ou moins": [
    "plus ou moins",
    "annonce plus",
    "annonce moins",
    "valeur supérieure",
    "valeur superieure",
    "valeur inférieure",
    "valeur inferieure",
    "égalité",
    "egalite",
  ],
  "réussite d'une prédiction": [
    "prédiction réussie",
    "prediction reussie",
    "annonce réussie",
    "annonce reussie",
  ],
  "échec d'une prédiction": [
    "prédiction ratée",
    "prediction ratee",
    "prédiction incorrecte",
    "prediction incorrecte",
    "annonce ratée",
    "annonce ratee",
    "en cas d'échec",
  ],
  "arrêt volontaire et sécurisation": [
    "arrêt volontaire",
    "arret volontaire",
    "s'arrêter",
    "s arreter",
    "sécuriser",
    "securiser",
    "minimum trois cartes",
  ],
  "purple couleur": [
    "purple couleur",
    "couleur annoncée",
    "couleur annoncee",
    "couleur + atout",
  ],
  "purple tarot": [
    "purple tarot",
    "purple atout",
    "rouge noire atout",
    "rouge noire et atout",
  ],
  "purple bout": ["purple bout", "bout", "purple avec bout"],
  poignée: [
    "poignée",
    "poignee",
    "atouts consécutifs",
    "atouts consecutifs",
  ],
  "double poignée": ["double poignée", "double poignee", "5 atouts"],
  "triple poignée": [
    "triple poignée",
    "triple poignee",
    "6 atouts",
    "cul sec atouts",
  ],
  "misère d’atout": [
    "misère",
    "misere",
    "sans atout",
    "6 cartes sans atout",
  ],
  "annonce du petit": ["petit", "le petit", "accent du sud"],
  "petit au bout": ["petit au bout", "dernier pli", "petit dernier pli"],
  "poteau ou bout": [
    "poteau",
    "bout",
    "annoncer un bout",
    "annoncer un poteau",
  ],
  "je pisse": [
    "je pisse",
    "pisse",
    "3 atouts d’affilée",
    "3 atouts d'affilee",
  ],
  "j’ouvre à une couleur": [
    "j’ouvre",
    "j'ouvre",
    "ouvre couleur",
    "ouvrir à une couleur",
  ],
  "21": ["21", "vingt-et-un", "vingt et un"],
  excuse: ["excuse", "joker"],
  "défi du dealer": [
    "défi dealer",
    "defi dealer",
    "paquet sur la tête",
    "paquet sur sa tete",
  ],
  "tu gardes": [
    "tu gardes",
    "tu gardes sans",
    "tu gardes contre",
    "x2",
    "x4",
    "x8",
  ],
  sandwich: [
    "sandwich",
    "encadrée",
    "encadree",
    "même valeur",
    "meme valeur",
  ],
  "ça coupe": ["ça coupe", "ca coupe", "coupe", "prochaine carte atout"],
  dealer: [
    "dealer",
    "regarde les cartes",
    "changer l’ordre",
    "changer l'ordre",
  ],
  "avis du dealer": [
    "avis du dealer",
    "vote",
    "majorité",
    "majorite",
    "destin liés",
    "destin lies",
  ],
  rois: [
    "roi",
    "rois",
    "partager les gorgées",
    "partager les gorgees",
  ],
  épicerie: [
    "épicier",
    "epicier",
    "épicerie",
    "epicerie",
    "épicerie fine",
    "epicerie fine",
  ],
  chien: [
    "chien",
    "remplacer ses gorgées",
    "remplacer ses gorgees",
    "6 cartes maximum",
  ],
  paquet: ["paquet", "merci", "verre d’eau", "verre d'eau"],
  divers: [
    "perdu",
    "ne sait plus jouer",
    "renverse un verre",
    "tu la chutes",
  ],
};
