export const RULE_ALIASES: Record<string, string[]> = {
  présentation: [
    "présentation",
    "presentation",
    "c'est quoi purple tarot",
    "principe du jeu",
  ],
  matériel: [
    "matériel",
    "materiel",
    "nombre de joueurs",
    "combien de joueurs",
    "78 cartes",
  ],
  objectif: ["objectif", "but du jeu", "comment gagner", "fin de manche"],
  dealer: [
    "dealer",
    "rôle du dealer",
    "role du dealer",
    "qui révèle les cartes",
    "qui revele les cartes",
  ],
  "joueur actif": ["joueur actif", "à qui de jouer", "a qui de jouer"],
  pli: ["pli", "cartes du pli", "taille du pli", "série", "serie"],
  annonce: [
    "annonce",
    "pari",
    "annonce perdue",
    "annonce réussie",
    "annonce reussie",
  ],
  "principes fondamentaux": [
    "principes fondamentaux",
    "modifier annonce",
    "annonce verrouillée",
    "annonce verrouillee",
    "désaccord",
    "desaccord",
  ],
  "valeur des cartes": [
    "valeur des cartes",
    "valeur as",
    "valeur valet",
    "valeur cavalier",
    "valeur dame",
    "valeur roi",
    "valeur atout",
    "cinquième couleur",
    "cinquieme couleur",
  ],
  "déroulement d'un tour": [
    "déroulement d'un tour",
    "deroulement d'un tour",
    "comment se passe un tour",
    "passer son tour",
    "trois cartes réussies",
    "trois cartes reussies",
    "combien de gorgées",
    "combien de gorgees",
  ],
  rouge: ["rouge", "annonce rouge", "carte rouge"],
  noir: ["noir", "annonce noir", "carte noire"],
  plus: ["plus", "annonce plus", "strictement supérieure", "strictement superieure"],
  moins: ["moins", "annonce moins", "strictement inférieure", "strictement inferieure"],
  intérieur: ["intérieur", "interieur", "annonce intérieur", "entre deux cartes"],
  extérieur: ["extérieur", "exterieur", "annonce extérieur", "en dehors des deux"],
  couleur: ["couleur", "annonce couleur", "couleur annoncée", "couleur annoncee"],
  purple: ["purple", "purple classique", "rouge et noire", "rouge noire"],
  "purple couleur": [
    "purple couleur",
    "couleur plus atout",
    "couleur + atout",
  ],
  "purple atout": [
    "purple atout",
    "purple tarot",
    "rouge noire atout",
    "rouge noire et atout",
  ],
  "purple bout": ["purple bout", "purple avec bout", "rouge noire bout"],
  poignée: ["poignée", "poignee", "3 atouts", "trois atouts"],
  "double poignée": ["double poignée", "double poignee", "5 atouts", "cinq atouts"],
  "triple poignée": ["triple poignée", "triple poignee", "6 atouts", "six atouts"],
  "misère d'atout": [
    "misère d'atout",
    "misere d'atout",
    "misère",
    "misere",
    "sans atout",
    "6 cartes sans atout",
  ],
  "j'ouvre à une couleur": [
    "j'ouvre",
    "j ouvre",
    "ouvrir à une couleur",
    "ouvrir a une couleur",
    "première annonce",
    "premiere annonce",
  ],
  contrats: [
    "contrat",
    "contrats",
    "tu gardes",
    "garde sans",
    "garde contre",
    "x2",
    "x4",
    "x8",
  ],
  "je pisse": [
    "je pisse",
    "pisse",
    "3 atouts consécutifs",
    "3 atouts consecutifs",
  ],
  "ça coupe": ["ça coupe", "ca coupe", "coupe", "prochaine carte atout"],
  "le petit": ["petit", "le petit", "atout 1", "accent du sud"],
  "le 21": ["21", "vingt-et-un", "vingt et un", "atout 21"],
  "l'excuse": [
    "excuse",
    "joker absolu",
    "paquet sur la tête",
    "paquet sur sa tete",
    "défi dealer",
    "defi dealer",
  ],
  "les rois": [
    "roi",
    "rois",
    "partager les gorgées",
    "partager les gorgees",
  ],
  "l'avis du dealer": [
    "avis du dealer",
    "vote",
    "majorité",
    "majorite",
    "destins liés",
    "destins lies",
  ],
  "le chien": [
    "chien",
    "six cartes maximum",
    "6 cartes maximum",
    "stocker les gorgées",
    "stocker les gorgees",
    "dernier dealer",
  ],
  "faire l'épicier": ["faire l'épicier", "faire l epicier", "épicier", "epicier"],
  "épicerie fine": ["épicerie fine", "epicerie fine", "trop prudent"],
  divers: [
    "merci paquet",
    "dire merci",
    "verre d'eau",
    "regarder les cartes",
    "modifier l'ordre",
    "joueur perdu",
    "renverse son verre",
    "tu la chutes",
  ],
  "esprit du jeu": [
    "esprit du jeu",
    "fair play",
    "arbitrage",
    "décision de la table",
    "decision de la table",
  ],
};
